name: ci

on:
  push:
    branches:
      - main
  schedule:
    - cron: "1,3,4,7 * * * *"
permissions:
  contents: write
jobs:
  autogreen:
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v3

      - name: Auto green
        run: |
          git config --local user.email "xucong754802892@gmail.com"
          git config --local user.name "xufeiwu123"
          git remote set-url origin https://${{ github.actor }}:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
          git pull --rebase
          git commit --allow-empty -m "a commit a day keeps your girlfriend away"
          git push
